version: '3'

services:
  ai-agent-web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8080:8001"  # Map port 8080 on host to port 8001 in container
    volumes:
      - research_db:/app/research_db
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SERPER_API_KEY=${SERPER_API_KEY}
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

volumes:
  research_db:
    driver: local