version: '3'

services:
  ai-agent:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - research_db:/app/research_db
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SERPER_API_KEY=${SERPER_API_KEY}
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

volumes:
  research_db:
    driver: local